# Generated by Django 5.2.2 on 2025-06-11 08:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=10, verbose_name='网格价格')),
                ('investment_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15, verbose_name='投资金额')),
                ('grid_type', models.CharField(choices=[('single', '单一网格'), ('small', '小网格'), ('medium', '中网格'), ('large', '大网格')], max_length=10, verbose_name='网格类型')),
                ('grid_index', models.IntegerField(default=0, verbose_name='网格序号')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='卖出价格')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='是否已触发')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格等级',
                'verbose_name_plural': '网格等级',
                'db_table': 'grid_levels',
            },
        ),
        migrations.CreateModel(
            name='GridPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(blank=True, null=True, verbose_name='快照日期')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总盈利')),
                ('realized_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已实现盈利')),
                ('unrealized_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='未实现盈利')),
                ('total_position', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='总持仓')),
                ('kept_profit_position', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='利润保留持仓')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('completed_pairs', models.IntegerField(default=0, verbose_name='完成交易对数')),
                ('invested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已投入金额')),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='可用金额')),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=10, verbose_name='当前价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网格性能快照',
                'verbose_name_plural': '网格性能快照',
                'db_table': 'grid_performance_snapshots',
            },
        ),
        migrations.CreateModel(
            name='GridPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='计划描述')),
                ('base_price', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=10, verbose_name='基准价格')),
                ('min_price', models.DecimalField(decimal_places=4, default=Decimal('50.0000'), help_text='压力测试最低价格，用于风险控制', max_digits=10, verbose_name='最低价格')),
                ('max_price', models.DecimalField(decimal_places=4, default=Decimal('200.0000'), max_digits=10, verbose_name='最高价格')),
                ('max_drawdown_percent', models.DecimalField(decimal_places=4, default=Decimal('50.00'), help_text='压力测试参数，如50%下跌', max_digits=8, verbose_name='最大下跌比例')),
                ('base_investment', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15, verbose_name='基础投资金额')),
                ('max_investment', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15, verbose_name='最大投资金额')),
                ('status', models.CharField(choices=[('active', '运行中'), ('paused', '暂停'), ('stopped', '已停止'), ('completed', '已完成')], default='active', max_length=20, verbose_name='状态')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总盈利')),
                ('realized_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已实现盈利')),
                ('kept_profit_shares', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='保留利润份额')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('buy_trades', models.IntegerField(default=0, verbose_name='买入次数')),
                ('sell_trades', models.IntegerField(default=0, verbose_name='卖出次数')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='累计投入资金')),
                ('available_funds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='可用资金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间')),
            ],
            options={
                'verbose_name': '网格计划',
                'verbose_name_plural': '网格计划',
                'db_table': 'grid_plans',
            },
        ),
        migrations.CreateModel(
            name='GridSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.CharField(max_length=36, unique=True, verbose_name='模拟ID')),
                ('config_data', models.JSONField(verbose_name='配置数据')),
                ('simulation_params', models.JSONField(verbose_name='模拟参数')),
                ('simulation_results', models.JSONField(verbose_name='模拟结果')),
                ('performance_metrics', models.JSONField(verbose_name='性能指标')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '网格模拟',
                'verbose_name_plural': '网格模拟',
                'db_table': 'grid_simulations',
            },
        ),
        migrations.CreateModel(
            name='GridStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='策略描述')),
                ('version', models.CharField(choices=[('1.0', '基础网格1.0'), ('2.0', '进阶网格2.0'), ('2.1', '留利润策略'), ('2.2', '逐格加码策略'), ('2.3', '一网打尽策略')], default='1.0', max_length=10, verbose_name='策略版本')),
                ('grid_interval_percent', models.DecimalField(decimal_places=4, default=Decimal('5.0000'), help_text='如5%填5.0000', max_digits=8, verbose_name='网格间距百分比')),
                ('keep_profit', models.BooleanField(default=False, verbose_name='启用留利润策略')),
                ('profit_keep_ratio', models.DecimalField(decimal_places=4, default=Decimal('100.00'), help_text='保留利润的百分比，100表示全部保留', max_digits=8, verbose_name='利润保留比例')),
                ('progressive_investment', models.BooleanField(default=False, verbose_name='启用逐格加码')),
                ('investment_increase_percent', models.DecimalField(decimal_places=4, default=Decimal('5.00'), help_text='每格投入增加的百分比', max_digits=8, verbose_name='加码百分比')),
                ('start_increase_from_grid', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='从第几格开始加码')),
                ('multi_grid', models.BooleanField(default=False, verbose_name='启用多重网格')),
                ('small_grid_percent', models.DecimalField(decimal_places=4, default=Decimal('5.00'), max_digits=8, verbose_name='小网格间距')),
                ('medium_grid_percent', models.DecimalField(decimal_places=4, default=Decimal('15.00'), max_digits=8, verbose_name='中网格间距')),
                ('large_grid_percent', models.DecimalField(decimal_places=4, default=Decimal('30.00'), max_digits=8, verbose_name='大网格间距')),
                ('small_grid_ratio', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='小网格资金比例')),
                ('medium_grid_ratio', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='中网格资金比例')),
                ('large_grid_ratio', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='大网格资金比例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格策略',
                'verbose_name_plural': '网格策略',
                'db_table': 'grid_strategies',
            },
        ),
        migrations.CreateModel(
            name='GridTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='模板描述')),
                ('template_data', models.JSONField(verbose_name='模板数据')),
                ('category', models.CharField(choices=[('conservative', '保守型'), ('balanced', '平衡型'), ('aggressive', '激进型'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='模板分类')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格模板',
                'verbose_name_plural': '网格模板',
                'db_table': 'grid_templates',
            },
        ),
        migrations.CreateModel(
            name='GridTradePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='盈利金额')),
                ('profit_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, verbose_name='盈利率')),
                ('kept_profit_shares', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='保留利润份额')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格交易对',
                'verbose_name_plural': '网格交易对',
                'db_table': 'grid_trade_pairs',
            },
        ),
        migrations.CreateModel(
            name='GridOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=10, verbose_name='订单价格')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=15, verbose_name='订单数量')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='订单金额')),
                ('order_type', models.CharField(choices=[('buy', '买入订单'), ('sell', '卖出订单')], max_length=10, verbose_name='订单类型')),
                ('status', models.CharField(choices=[('pending', '待成交'), ('filled', '已成交'), ('cancelled', '已取消'), ('partial', '部分成交')], default='pending', max_length=20, verbose_name='状态')),
                ('filled_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='已成交数量')),
                ('filled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已成交金额')),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='成交价格')),
                ('profit_kept_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='保留利润数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('grid_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='grid.gridlevel', verbose_name='网格等级')),
            ],
            options={
                'verbose_name': '网格订单',
                'verbose_name_plural': '网格订单',
                'db_table': 'grid_orders',
                'ordering': ['price'],
            },
        ),
    ]
