# Generated by Django 5.2.2 on 2025-06-09 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='订单价格')),
                ('quantity', models.IntegerField(verbose_name='订单数量')),
                ('order_type', models.CharField(choices=[('buy', '买入订单'), ('sell', '卖出订单')], max_length=10, verbose_name='订单类型')),
                ('status', models.CharField(choices=[('pending', '待成交'), ('filled', '已成交'), ('cancelled', '已取消'), ('partial', '部分成交')], default='pending', max_length=20, verbose_name='状态')),
                ('filled_quantity', models.IntegerField(default=0, verbose_name='已成交数量')),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='成交价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
            ],
            options={
                'verbose_name': '网格订单',
                'verbose_name_plural': '网格订单',
                'db_table': 'grid_orders',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='GridPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='计划描述')),
                ('base_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='基准价格')),
                ('grid_interval', models.DecimalField(decimal_places=4, help_text='价格间距或百分比', max_digits=8, verbose_name='网格间距')),
                ('interval_type', models.CharField(choices=[('fixed', '固定金额'), ('percent', '百分比')], default='percent', max_length=10, verbose_name='间距类型')),
                ('min_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最低价格')),
                ('max_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最高价格')),
                ('base_quantity', models.IntegerField(verbose_name='基础交易数量')),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='最大投资金额')),
                ('status', models.CharField(choices=[('active', '运行中'), ('paused', '暂停'), ('stopped', '已停止'), ('completed', '已完成')], default='active', max_length=20, verbose_name='状态')),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总盈利')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('buy_trades', models.IntegerField(default=0, verbose_name='买入次数')),
                ('sell_trades', models.IntegerField(default=0, verbose_name='卖出次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间')),
            ],
            options={
                'verbose_name': '网格计划',
                'verbose_name_plural': '网格计划',
                'db_table': 'grid_plans',
            },
        ),
    ]
