# Generated by Django 5.2.2 on 2025-06-11 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0001_initial'),
        ('stocks', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gridorder',
            name='trading_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.tradingrecord', verbose_name='交易记录'),
        ),
        migrations.AddField(
            model_name='gridplan',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='交易标的'),
        ),
        migrations.AddField(
            model_name='gridplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='gridperformancesnapshot',
            name='grid_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='grid.gridplan', verbose_name='网格计划'),
        ),
        migrations.AddField(
            model_name='gridorder',
            name='grid_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='grid.gridplan', verbose_name='网格计划'),
        ),
        migrations.AddField(
            model_name='gridlevel',
            name='grid_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='grid.gridplan', verbose_name='网格计划'),
        ),
        migrations.AddField(
            model_name='gridsimulation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='gridplan',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.gridstrategy', verbose_name='使用策略'),
        ),
        migrations.AddField(
            model_name='gridtemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='gridtradepair',
            name='buy_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_pair', to='grid.gridorder', verbose_name='买入订单'),
        ),
        migrations.AddField(
            model_name='gridtradepair',
            name='grid_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_pairs', to='grid.gridplan', verbose_name='网格计划'),
        ),
        migrations.AddField(
            model_name='gridtradepair',
            name='sell_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_pair', to='grid.gridorder', verbose_name='卖出订单'),
        ),
        migrations.AddIndex(
            model_name='gridperformancesnapshot',
            index=models.Index(fields=['grid_plan', 'snapshot_date'], name='grid_perfor_grid_pl_be940f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gridperformancesnapshot',
            unique_together={('grid_plan', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['grid_plan'], name='grid_orders_grid_pl_619fba_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['status'], name='grid_orders_status_796afa_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['order_type'], name='grid_orders_order_t_0c42e7_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['price'], name='grid_orders_price_eff522_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['created_at'], name='grid_orders_created_7a78c8_idx'),
        ),
        migrations.AddIndex(
            model_name='gridlevel',
            index=models.Index(fields=['grid_plan', 'price'], name='grid_levels_grid_pl_ca9929_idx'),
        ),
        migrations.AddIndex(
            model_name='gridlevel',
            index=models.Index(fields=['grid_plan', 'is_triggered'], name='grid_levels_grid_pl_3a00de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gridlevel',
            unique_together={('grid_plan', 'price', 'grid_type')},
        ),
        migrations.AddIndex(
            model_name='gridsimulation',
            index=models.Index(fields=['user'], name='grid_simula_user_id_b4dee3_idx'),
        ),
        migrations.AddIndex(
            model_name='gridsimulation',
            index=models.Index(fields=['status'], name='grid_simula_status_2a9198_idx'),
        ),
        migrations.AddIndex(
            model_name='gridsimulation',
            index=models.Index(fields=['-created_at'], name='grid_simula_created_a010c6_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['user'], name='grid_plans_user_id_bc4d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['stock'], name='grid_plans_stock_i_6ceeed_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['status'], name='grid_plans_status_52693d_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['user', 'stock'], name='grid_plans_user_id_37f982_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtemplate',
            index=models.Index(fields=['category'], name='grid_templa_categor_73756b_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtemplate',
            index=models.Index(fields=['is_public'], name='grid_templa_is_publ_cc9105_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtemplate',
            index=models.Index(fields=['user'], name='grid_templa_user_id_56f085_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtemplate',
            index=models.Index(fields=['-usage_count'], name='grid_templa_usage_c_1c9ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtradepair',
            index=models.Index(fields=['grid_plan'], name='grid_trade__grid_pl_067ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtradepair',
            index=models.Index(fields=['is_completed'], name='grid_trade__is_comp_a6753d_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtradepair',
            index=models.Index(fields=['completed_at'], name='grid_trade__complet_4f3a85_idx'),
        ),
    ]
