# Generated by Django 5.2.2 on 2025-06-09 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0001_initial'),
        ('stocks', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gridorder',
            name='trading_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.tradingrecord', verbose_name='交易记录'),
        ),
        migrations.AddField(
            model_name='gridplan',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='交易标的'),
        ),
        migrations.AddField(
            model_name='gridplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='gridorder',
            name='grid_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='grid.gridplan', verbose_name='网格计划'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['user'], name='grid_plans_user_id_bc4d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['stock'], name='grid_plans_stock_i_6ceeed_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['status'], name='grid_plans_status_52693d_idx'),
        ),
        migrations.AddIndex(
            model_name='gridplan',
            index=models.Index(fields=['user', 'stock'], name='grid_plans_user_id_37f982_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['grid_plan'], name='grid_orders_grid_pl_619fba_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['status'], name='grid_orders_status_796afa_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['order_type'], name='grid_orders_order_t_0c42e7_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['price'], name='grid_orders_price_eff522_idx'),
        ),
    ]
