# Generated by Django 5.2.2 on 2025-06-11 08:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField(verbose_name='日期')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='现金余额')),
                ('stock_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='股票市值')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总资产')),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='当日盈亏')),
                ('daily_return_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='当日收益率')),
                ('cumulative_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='累计盈亏')),
                ('cumulative_return_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='累计收益率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日资产',
                'verbose_name_plural': '每日资产',
                'db_table': 'daily_balances',
                'ordering': ['-balance_date'],
                'indexes': [models.Index(fields=['user'], name='daily_balan_user_id_0daacc_idx'), models.Index(fields=['balance_date'], name='daily_balan_balance_08e9d9_idx'), models.Index(fields=['user', 'balance_date'], name='daily_balan_user_id_205b4e_idx')],
                'unique_together': {('user', 'balance_date')},
            },
        ),
        migrations.CreateModel(
            name='ProfitLossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', '日'), ('weekly', '周'), ('monthly', '月'), ('quarterly', '季度'), ('yearly', '年')], max_length=20, verbose_name='统计周期')),
                ('period_date', models.DateField(verbose_name='统计日期')),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已实现盈亏')),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='浮动盈亏')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总盈亏')),
                ('return_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='收益率')),
                ('total_trades', models.IntegerField(default=0, verbose_name='交易次数')),
                ('buy_trades', models.IntegerField(default=0, verbose_name='买入次数')),
                ('sell_trades', models.IntegerField(default=0, verbose_name='卖出次数')),
                ('total_investment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总投入')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='当前价值')),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总佣金')),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '盈亏记录',
                'verbose_name_plural': '盈亏记录',
                'db_table': 'profit_loss_records',
                'ordering': ['-period_date'],
                'indexes': [models.Index(fields=['user'], name='profit_loss_user_id_de198a_idx'), models.Index(fields=['stock'], name='profit_loss_stock_i_680527_idx'), models.Index(fields=['period_type'], name='profit_loss_period__5194a2_idx'), models.Index(fields=['period_date'], name='profit_loss_period__0cd132_idx'), models.Index(fields=['user', 'period_type', 'period_date'], name='profit_loss_user_id_788954_idx')],
                'unique_together': {('user', 'stock', 'period_type', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='TradingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='盈利交易次数')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='亏损交易次数')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='胜率')),
                ('profit_loss_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='盈亏比')),
                ('total_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总收益')),
                ('total_return_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='总收益率')),
                ('average_return_per_trade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='平均每笔收益')),
                ('max_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='最大盈利')),
                ('max_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='最大亏损')),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='最大回撤')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='夏普比率')),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='波动率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易表现',
                'verbose_name_plural': '交易表现',
                'db_table': 'trading_performance',
                'ordering': ['-end_date'],
                'indexes': [models.Index(fields=['user'], name='trading_per_user_id_6ec904_idx'), models.Index(fields=['stock'], name='trading_per_stock_i_5e5e19_idx'), models.Index(fields=['start_date', 'end_date'], name='trading_per_start_d_81d399_idx')],
            },
        ),
    ]
