# Generated by Django 5.2.2 on 2025-06-11 08:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('grid', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总持仓数量')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='可用数量')),
                ('frozen_quantity', models.IntegerField(default=0, verbose_name='冻结数量')),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='平均成本价')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='总成本')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='当前价格')),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='市值')),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='浮动盈亏')),
                ('unrealized_pnl_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, verbose_name='浮动盈亏率')),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='已实现盈亏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_trade_date', models.DateTimeField(blank=True, null=True, verbose_name='最后交易日期')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='标的')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'db_table': 'positions',
                'indexes': [models.Index(fields=['user'], name='positions_user_id_311f8d_idx'), models.Index(fields=['user', 'stock'], name='positions_user_id_164fe4_idx')],
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='TradingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.CharField(help_text='格式：20250101', max_length=8, verbose_name='成交日期')),
                ('trade_time', models.CharField(help_text='格式：09:31', max_length=5, verbose_name='成交时间')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='成交价格')),
                ('quantity', models.IntegerField(verbose_name='成交数量')),
                ('trade_type', models.CharField(choices=[('b', '买入'), ('s', '卖出')], max_length=1, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='成交金额')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='佣金')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='过户费')),
                ('stamp_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='印花税')),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总费用')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='买入时为负数（支出），卖出时为正数（收入）', max_digits=15, null=True, verbose_name='净额')),
                ('notes', models.CharField(blank=True, help_text='如建仓、盈利卖出一部分', max_length=200, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('cancelled', '已取消'), ('pending', '待成交')], default='completed', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('commission_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.commissionplan', verbose_name='佣金方案')),
                ('grid_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.gridplan', verbose_name='网格计划')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='交易标的')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'trading_records',
                'ordering': ['-trade_date', '-trade_time'],
                'indexes': [models.Index(fields=['user'], name='trading_rec_user_id_f0a17f_idx'), models.Index(fields=['stock'], name='trading_rec_stock_i_ca01c7_idx'), models.Index(fields=['trade_date'], name='trading_rec_trade_d_e34428_idx'), models.Index(fields=['trade_type'], name='trading_rec_trade_t_3d49b1_idx'), models.Index(fields=['user', 'stock'], name='trading_rec_user_id_3173c4_idx'), models.Index(fields=['user', 'trade_date'], name='trading_rec_user_id_00837a_idx'), models.Index(fields=['stock', 'trade_date'], name='trading_rec_stock_i_c7e707_idx')],
            },
        ),
    ]
