# Generated by Django 5.2.2 on 2025-06-09 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='如 SZ.510300', max_length=20, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(help_text='如 沪深300ETF', max_length=100, verbose_name='股票名称')),
                ('market', models.CharField(help_text='如 SZ、SH', max_length=10, verbose_name='市场')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='当前价格')),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='昨收价')),
                ('total_shares', models.BigIntegerField(blank=True, null=True, verbose_name='总股本')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='总市值')),
                ('category', models.CharField(choices=[('stock', '股票'), ('etf', 'ETF'), ('fund', '基金'), ('bond', '债券')], default='stock', max_length=50, verbose_name='类别')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='行业')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='板块')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可交易')),
                ('is_st', models.BooleanField(default=False, verbose_name='是否ST股票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_trade_date', models.DateTimeField(blank=True, null=True, verbose_name='最后交易日期')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
                'db_table': 'stocks',
                'indexes': [models.Index(fields=['symbol'], name='stocks_symbol_7bc68d_idx'), models.Index(fields=['market'], name='stocks_market_143d55_idx'), models.Index(fields=['category'], name='stocks_categor_b7dbca_idx'), models.Index(fields=['is_active'], name='stocks_is_acti_fcb4d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最低价')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票价格',
                'verbose_name_plural': '股票价格',
                'db_table': 'stock_prices',
                'indexes': [models.Index(fields=['trade_date'], name='stock_price_trade_d_9f51e9_idx'), models.Index(fields=['stock', 'trade_date'], name='stock_price_stock_i_b45ab1_idx')],
                'unique_together': {('stock', 'trade_date')},
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户自定义别名')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='目标价格')),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='止损价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自选股',
                'verbose_name_plural': '自选股',
                'db_table': 'watch_lists',
                'indexes': [models.Index(fields=['user'], name='watch_lists_user_id_40545d_idx'), models.Index(fields=['user', 'stock'], name='watch_lists_user_id_656a15_idx')],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
